name: PGM-conda-env
channels:
  - defaults
dependencies:
  - python>=3.7
  - pip
  - numpy
  - requests
  - pandas
  - matplotlib
  - tensorboard
  - jupyterlab
  - python-multipart
  - pytorch
  - torchvision
  - cudatoolkit>=10.0
  - opencv
  - ipywidgets
  - scikit-learn
  - imbalanced-learn
  - opencv
  - wget
  - pip:
    - tqdm
    - wandb
